task_type: classification
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NHWC
  reverse_channels: false
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  target_device: null
  input_optimization: false
  input_data_layout: NHWC
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.007812
  - 0.007812
  - 0.007812
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: mobilenet_v3-small-minimalistic_224_1.0_float.tflite
  model_id: cl-0270
  input_details: null
  output_details: null
  num_inputs: 1
  artifacts_folder: artifacts
metric:
  label_offset_pred: -1
model_info:
  metric_reference:
    accuracy_top1%: 61.9
