task_type: segmentation
input_dataset: ade20k32
preprocess:
  resize:
  - 512
  - 512
  crop:
  - 512
  - 512
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 3
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.015625
  - 0.015625
  - 0.015625
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: fpn_aspp_regnetx800mf_edgeailite_512x512_20210312_outby4.onnx
  model_id: ss-8700
  input_details: null
  output_details: null
  num_inputs: 1
  artifacts_folder: artifacts
postprocess:
  save_output: false
model_info:
  metric_reference:
    accuracy_mean_iou%: 53.16
