task_type: segmentation
input_dataset: voc2012
preprocess:
  resize:
  - 512
  - 512
  crop:
  - 512
  - 512
  data_layout: NHWC
  reverse_channels: false
  backend: cv2
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  target_device: null
  input_optimization: false
  input_data_layout: NHWC
  input_mean:
  - 127.5
  - 127.5
  - 127.5
  input_scale:
  - 0.007843
  - 0.007843
  - 0.007843
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: deeplabv3_mnv2_dm05_pascal_trainaug_512x512.tflite
  model_id: ss-2590
  input_details: null
  output_details: null
  num_inputs: 1
  artifacts_folder: artifacts
postprocess:
  save_output: false
model_info:
  metric_reference:
    accuracy_mean_iou%: 70.19
