task_type: detection
input_dataset: widerface
preprocess:
  resize: 640
  crop: 640
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  runtime_options:
    advanced_options:output_feature_16bit_names_list: 996, 711, 712, 713, 727, 728,
      728, 743, 744, 745
    advanced_options:params_16bit_names_list: ''
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: yolox_s_lite_640x640_20220307_model.prototxt
  model_path: yolox_s_lite_640x640_20220307_model.onnx
  model_id: od-8420
  input_details: null
  output_details: null
  num_inputs: 1
  artifacts_folder: artifacts
postprocess:
  detection_threshold: 0.3
  save_output: false
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
metric:
  label_offset_pred:
    0: 1
    1: 2
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 31.62
