task_type: object_6d_pose_estimation
input_dataset: ycbv
postprocess:
  detection_threshold: 0.3
  save_output: false
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
preprocess:
  resize:
  - 480
  - 640
  crop:
  - 480
  - 640
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  target_device: null
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  runtime_options:
    advanced_options:output_feature_16bit_names_list: 597, 826, 833, 834, 844, 854,
      855, 1021, 1028, 1029, 1039, 1049, 1050, 1216, 1223, 1224, 1234, 1244, 1245
    advanced_options:params_16bit_names_list: ''
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: yolox_s_object_pose_ti_lite_metaarch_640x480.prototxt
  model_path: yolox_s_object_pose_ti_lite_640x480_57p75.onnx
  model_id: 6dpose-7200
  input_details: null
  output_details: null
  num_inputs: 1
  artifacts_folder: artifacts
model_info:
  metric_reference: {}
